import { Manrope } from 'next/font/google'
import './globals.css'
import { HeaderProvider } from '@/hooks/useHeader'
import { Layout } from '@/components/Layouts/Main'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Qlnkr',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <HeaderProvider>
          <Layout>
            {children}
          </Layout>
        </HeaderProvider>
      </body>
    </html>
  )
}
